### PR TITLE
[WIP]

### PR DESCRIPTION
**Pull request by LorbusChris**
Refactor to use react-engine for universal rendering.

### CODE REVIEW

**Comment by LorbusChris** [comment]
@ericelliott do you mind having a look? 
Currently only the server side rendering is working. 
I havent yet found a way to call document.addEventListener as document (and window) is defined (see at the end of default.js.) Also I'm not sure whether I did the route setup correctly. 
Am I supposed to call keystone/server/initViewEngine.js?

This is by far not finished, I plan on ripping out jade entirely (as I see it all the logic belongs in js) and setting up i18n with react-intl and later css with jss or react-jss. 
I dont have any noteworthy experience with JS so I'd appreciate any feedback, really!
If you'd rather have me make a PR to your repo I can do that, too.

**Comment by ericelliott** [comment]
Hi @LorbusChris,

When I started looking at universal routing & rendering, my first thought was to use React-Engine, but after giving it a try, I didn't see the value that I hoped it would provide.

What is the purpose of this refactor? What does it give us that we don't already have?

Note that the current version of universal route & render from this boilerplate has been merged into Keystone 0.4.x. I'm currently working on a standard way to pass data into the components using Redux via React-Redux.

screen shot 2016-01-06 at 8 36 00 pm

Just add the following to your `Keystone.init()`:

```js
	'react routes': componentRoutes,
```

**Comment by ericelliott** [comment]
Also worth noting, since you mentioned it, I've also added language negotiation to Keystone 0.4.x:

screen shot 2016-01-14 at 8 36 45 pm

**Comment by LorbusChris** [comment]
Thanks for the great boilerplate, support and quick response! :+1:  
The name is actually a bit confusing, it's a refactor of my first approach yesterday.
What I did is put together a React-Bootstrap Navbar Component to get some simple UI and Routing feeling.
There isnt any added value in it per se (and certainly not in its current state). However, and especially because I'm rather new to JS, I'd like to keep this tech-stack as minimalistic but bleeding-edge as possible. For me this means throwing out tech like jquery and jade (which here for me is just an abstraction of Layout and some logic which could be moved into React Components). 

So should I throw out all the express views? 
How else would I configure the (express) views? Not react-engine, not jade, not at all? Or are they required for keystone? Do I need them for SEO? 

I want to build a universal website/app with a keystone backend, r-router, r-intl, r-bootstrap, elemental and jss. Or at least try to do so :)

**Comment by ericelliott** [comment]
> For me this means throwing out tech like jquery and jade (which here for me is just an abstraction of Layout and some logic which could be moved into React Components).

I'm all for this, absolutely.

> So should I throw out all the express views? 

I was planning to finish the universal Redux data connection, and then my plan was to convert the existing views into React Routes.

> How else would I configure the (express) views? Not react-engine, not jade, not at all?

Not at all. In your own app, feel free to throw them away if you don't need them. As mentioned in the 0.4.x documentation, all you need to do to get universal routing & rendering is pass your React Routes into `Keystone.init()`. The Express views are only there for legacy reference. I plan to replace them completely with React Routes.

> I want to build a universal website/app with a keystone backend, r-router, r-intl, r-bootstrap, elemental and jss. Or at least try to do so :)

Yep.. that's what we're building here. You've stumbled into a work-in-progress. For instance, as you read this I'm working on auto-wiring Redux for universal routing & rendering that I hope to merge into Keystone core in a few days.

I'd love your help. I'm currently trying to fix the client-side Redux hookup in the [Universal React Boilerplate](https://github.com/cloverfield-tools/universal-react-boilerplate/tree/universal-fixes). Once that's done, I'll port the Redux hookup to Keystone, and implement a demo in this repo.

**Comment by LorbusChris** [comment]
Awesome. I'll have a look and see what I can do!

**Comment by ericelliott** [comment]
:+1:

**Pull request closed without merging**
